CREATE TABLE regiao_administrativa_tb (
    ID_POP_DOMIC_REGIONAL_2022 INTEGER PRIMARY KEY, 
    COD_REGIONAL INTEGER,
    NOME VARCHAR(50),
    SIGLA VARCHAR(10),
    AREA_KM NUMERIC,
    POPULACAO INTEGER,
    DOMICILIOS INTEGER,
    /* GEOMETRIA GEOMETRY, Utilizar apenas se tiver instalado o PostGis*/
    DENSIDADE_DEMOGRAFICA NUMERIC
);
