
CREATE TABLE pop_domicilios_regional_2022 (
    ID_POP_DOMIC_REGIONAL_2022 BIGINT PRIMARY KEY, 

    COD_REGIONAL INTEGER,
    NOME VARCHAR(20),
    SIGLA VARCHAR(2),
    POPULACAO INTEGER,
    DOMICILIOS INTEGER,
    AREA_KM NUMERIC,
    GEOMETRIA GEOMETRY, 
	DENSIDADE_DEMOGRAFICA NUMERIC
);
