CREATE TABLE pessoas_cadunico (
    _id_sequencial_ BIGSERIAL PRIMARY KEY,

    PARENTESCO_RF VARCHAR(50),
    DATA_NASCIMENTO DATE,
    IDADE SMALLINT,
    SEXO VARCHAR(20),
    BOLSA_FAMILIA VARCHAR(3),
    POP_RUA VARCHAR(3),
    GRAU_INSTRUCAO VARCHAR(100),
    COR_RACA VARCHAR(30),
    FAIXA_RENDA_FAMILIAR_PER_CAPITA VARCHAR(100),
    VAL_REMUNERACAO_MES_PASSADO INTEGER,
    CRAS VARCHAR(150),
    REGIONAL VARCHAR(100),
    FAIXA_DESATUALIZACAO_CADASTRAL VARCHAR(50),
    MES_ANO_REFERENCIA CHAR(7),
    PCD VARCHAR(3),
    MUNICIPIO_NASCIMENTO VARCHAR(100),
    UF_NASCIMENTO CHAR(2),
    PAIS_ORIGEM VARCHAR(50),
    DATA_ATUALIZACAO_FAMILIA DATE,

    FAMILIA_GRUPO_POPULACIONAIS_TRADICIONAIS_EXPECIFICOS VARCHAR(100)
);