CREATE TABLE populacao_rua_bh (
    _id BIGSERIAL PRIMARY KEY,

    TEMPO_VIVE_NA_RUA VARCHAR(100),
    CONTATO_PARENTE_FORA_RUAS VARCHAR(100),

	DATA_NASCIMENTO DATE,
    IDADE SMALLINT,
    SEXO VARCHAR(20),
    BOLSA_FAMILIA VARCHAR(3),
    POP_RUA VARCHAR(3),
    GRAU_INSTRUCAO VARCHAR(100),
    COR_RACA VARCHAR(30),
    FAIXA_RENDA_FAMILIAR_PER_CAPITA VARCHAR(100),
    VAL_REMUNERACAO_MES_PASSADO INTEGER,
    CRAS VARCHAR(150),
    REGIONAL VARCHAR(100),
    FAIXA_DESATUALICACAO_CADASTRAL VARCHAR(50), 
    MES_ANO_REFERENCIA DATE         
);